namespace SeoDomainFinder.Core.Localization;

public static class SearchStrings
{
    public static string Get(string? language, string key, params object[] args)
    {
        var lang = SearchLocale.Normalize(language);
        if (!Strings.TryGetValue(lang, out var table) || !table.TryGetValue(key, out var template))
        {
            if (!En.TryGetValue(key, out template))
                return key;
        }

        return args.Length == 0 ? template : string.Format(template, args);
    }

    // SEO scorer
    private static readonly Dictionary<string, string> En = new()
    {
        ["seo.brandScoring"] = "brand scoring",
        ["seo.idealBrandLength"] = "ideal brand length (8-11)",
        ["seo.acceptableCoinedLength"] = "acceptable coined length",
        ["seo.lengthPenalty"] = "length penalty",
        ["seo.softMetaphorPortmanteau"] = "soft metaphor portmanteau",
        ["seo.literalPenalty"] = "literal '{0}' penalty",
        ["seo.singleConceptEvoked"] = "single concept evoked",
        ["seo.keywordMashupPenalty"] = "keyword mashup penalty",
        ["seo.genericSuffixPenalty"] = "generic suffix penalty",
        ["seo.evokes"] = "evokes '{0}'",
        ["seo.matches"] = "matches '{0}'",
        ["seo.goodLength"] = "good length (8-18)",
        ["seo.acceptableLength"] = "acceptable length",
        ["seo.longDomain"] = "long domain",
        ["seo.multiKeywordMatch"] = "multi-keyword match",
        ["seo.modifierKeyword"] = "modifier keyword",
        ["seo.genericName"] = "generic name",
        ["advice.noneFound"] = "No available domains after {0} of {1} checks ({2} taken or over budget). Try more TLDs or run another search.",
        ["advice.oneFound"] = "Only one option found: {0}{1}. Checked {2}/{3} names. Most were taken. Try more TLDs or search again for more coinages.",
        ["advice.multipleFound"] = "Found {0} options after {1}/{2} checks ({3} taken or over budget). Add more TLDs if you want additional choices.",
        ["warn.rateLimitIncomplete"] = "Many checks hit Porkbun rate limits. Results may be incomplete.",
        ["warn.porkbunNotConfigured"] = "Domain availability checks are unavailable (Porkbun API not configured on server).",
        ["warn.rateLimitRetry"] = "Many checks hit Porkbun rate limits. Please try again in a minute.",
        ["warn.hintUseLlm"] = "Try more invented brand names, add TLDs like .app or .dev, or raise the price limit.",
        ["warn.hintNoLlm"] = "Try shorter names, add a country TLD (e.g. .mx), raise the price limit, or enable AI.",
        ["warn.noAvailable"] = "Checked {0} domains; none available under ${1:F0}. {2}",
        ["warn.aiBriefFailed"] = "AI brief failed, using fallback: {0}",
        ["warn.aiAdviceFailed"] = "AI advice failed: {0}",
        ["warn.aiPlannerFailed"] = "AI planner failed: {0}",
        ["warn.aiPlannerNoValid"] = "AI planner returned no valid domains; checking heuristic names.",
        ["warn.aiPlannerNoValidQueue"] = "AI planner returned no valid domains; using heuristic queue.",
        ["warn.aiPlannerFailedHeuristic"] = "AI planner failed: {0}; checking heuristic names.",
        ["warn.aiPlannerFailedQueue"] = "AI planner failed, using heuristic queue: {0}",
        ["warn.llmNameGenFailed"] = "LLM name generation failed: {0}",
        ["warn.aiRefillFailed"] = "AI refill failed: {0}",
        ["brief.audience"] = "target customers for this business",
        ["brief.productSummaryEmpty"] = "A new business venture seeking a memorable domain name.",
        ["brief.productSummaryPrefix"] = "A business concept described as: {0}",
        ["brief.namingStyle1"] = "soft metaphor portmanteaus",
        ["brief.namingStyle2"] = "8-11 char opaque blends",
        ["brief.namingStyle3"] = "abstract coined brands",
        ["brief.vibeMemorable"] = "memorable",
        ["brief.vibeDistinctive"] = "distinctive",
        ["brief.tldStrategy"] = "short pronounceable .com names are usually taken; prefer 8-10 char opaque blends on .com",
        ["brief.defaultConceptVenture"] = "venture",
        ["brief.defaultConceptBrand"] = "brand"
    };

    private static readonly Dictionary<string, string> Es = new()
    {
        ["seo.brandScoring"] = "puntuación de marca",
        ["seo.idealBrandLength"] = "longitud ideal (8-11)",
        ["seo.acceptableCoinedLength"] = "longitud inventada aceptable",
        ["seo.lengthPenalty"] = "penalización por longitud",
        ["seo.softMetaphorPortmanteau"] = "portmanteau metafórico suave",
        ["seo.literalPenalty"] = "penalización literal '{0}'",
        ["seo.singleConceptEvoked"] = "evoca un solo concepto",
        ["seo.keywordMashupPenalty"] = "penalización por mezcla de palabras clave",
        ["seo.genericSuffixPenalty"] = "penalización por sufijo genérico",
        ["seo.evokes"] = "evoca '{0}'",
        ["seo.matches"] = "coincide con '{0}'",
        ["seo.goodLength"] = "buena longitud (8-18)",
        ["seo.acceptableLength"] = "longitud aceptable",
        ["seo.longDomain"] = "dominio largo",
        ["seo.multiKeywordMatch"] = "coincidencia con varias palabras clave",
        ["seo.modifierKeyword"] = "palabra modificadora",
        ["seo.genericName"] = "nombre genérico",
        ["advice.noneFound"] = "No hay dominios disponibles tras {0} de {1} comprobaciones ({2} ocupados o fuera de presupuesto). Prueba más TLDs u otra búsqueda.",
        ["advice.oneFound"] = "Solo una opción encontrada: {0}{1}. Se comprobaron {2}/{3} nombres. La mayoría estaban ocupados. Prueba más TLDs u otra búsqueda.",
        ["advice.multipleFound"] = "Se encontraron {0} opciones tras {1}/{2} comprobaciones ({3} ocupados o fuera de presupuesto). Añade más TLDs si quieres más opciones.",
        ["warn.rateLimitIncomplete"] = "Muchas comprobaciones alcanzaron el límite de Porkbun. Los resultados pueden estar incompletos.",
        ["warn.porkbunNotConfigured"] = "Las comprobaciones de disponibilidad no están disponibles (API de Porkbun no configurada en el servidor).",
        ["warn.rateLimitRetry"] = "Muchas comprobaciones alcanzaron el límite de Porkbun. Inténtalo de nuevo en un minuto.",
        ["warn.hintUseLlm"] = "Prueba más nombres de marca inventados, añade TLDs como .app o .dev, o sube el límite de precio.",
        ["warn.hintNoLlm"] = "Prueba nombres más cortos, añade un TLD de país (p. ej. .mx), sube el límite de precio o activa la IA.",
        ["warn.noAvailable"] = "Se comprobaron {0} dominios; ninguno disponible por debajo de ${1:F0}. {2}",
        ["warn.aiBriefFailed"] = "El brief de IA falló, usando respaldo: {0}",
        ["warn.aiAdviceFailed"] = "El análisis de IA falló: {0}",
        ["warn.aiPlannerFailed"] = "El planificador de IA falló: {0}",
        ["warn.aiPlannerNoValid"] = "El planificador de IA no devolvió dominios válidos; comprobando nombres heurísticos.",
        ["warn.aiPlannerNoValidQueue"] = "El planificador de IA no devolvió dominios válidos; usando cola heurística.",
        ["warn.aiPlannerFailedHeuristic"] = "El planificador de IA falló: {0}; comprobando nombres heurísticos.",
        ["warn.aiPlannerFailedQueue"] = "El planificador de IA falló, usando cola heurística: {0}",
        ["warn.llmNameGenFailed"] = "La generación de nombres con IA falló: {0}",
        ["warn.aiRefillFailed"] = "El relleno de IA falló: {0}",
        ["brief.audience"] = "clientes objetivo de este negocio",
        ["brief.productSummaryEmpty"] = "Un nuevo negocio que busca un nombre de dominio memorable.",
        ["brief.productSummaryPrefix"] = "Un concepto de negocio descrito como: {0}",
        ["brief.namingStyle1"] = "portmanteaus metafóricos suaves",
        ["brief.namingStyle2"] = "mezclas opacas de 8-11 caracteres",
        ["brief.namingStyle3"] = "marcas abstractas inventadas",
        ["brief.vibeMemorable"] = "memorable",
        ["brief.vibeDistinctive"] = "distintivo",
        ["brief.tldStrategy"] = "los nombres .com cortos y pronunciables suelen estar ocupados; preferir mezclas opacas de 8-10 caracteres en .com",
        ["brief.defaultConceptVenture"] = "empresa",
        ["brief.defaultConceptBrand"] = "marca"
    };

    private static readonly Dictionary<string, string> Pt = new()
    {
        ["seo.brandScoring"] = "pontuação de marca",
        ["seo.idealBrandLength"] = "comprimento ideal (8-11)",
        ["seo.acceptableCoinedLength"] = "comprimento inventado aceitável",
        ["seo.lengthPenalty"] = "penalidade por comprimento",
        ["seo.softMetaphorPortmanteau"] = "portmanteau metafórico suave",
        ["seo.literalPenalty"] = "penalidade literal '{0}'",
        ["seo.singleConceptEvoked"] = "evoca um único conceito",
        ["seo.keywordMashupPenalty"] = "penalidade por mistura de palavras-chave",
        ["seo.genericSuffixPenalty"] = "penalidade por sufixo genérico",
        ["seo.evokes"] = "evoca '{0}'",
        ["seo.matches"] = "corresponde a '{0}'",
        ["seo.goodLength"] = "bom comprimento (8-18)",
        ["seo.acceptableLength"] = "comprimento aceitável",
        ["seo.longDomain"] = "domínio longo",
        ["seo.multiKeywordMatch"] = "correspondência com várias palavras-chave",
        ["seo.modifierKeyword"] = "palavra modificadora",
        ["seo.genericName"] = "nome genérico",
        ["advice.noneFound"] = "Nenhum domínio disponível após {0} de {1} verificações ({2} ocupados ou acima do orçamento). Tente mais TLDs ou outra busca.",
        ["advice.oneFound"] = "Apenas uma opção encontrada: {0}{1}. Verificados {2}/{3} nomes. A maioria estava ocupada. Tente mais TLDs ou busque novamente.",
        ["advice.multipleFound"] = "Encontradas {0} opções após {1}/{2} verificações ({3} ocupados ou acima do orçamento). Adicione mais TLDs se quiser mais opções.",
        ["warn.rateLimitIncomplete"] = "Muitas verificações atingiram o limite do Porkbun. Os resultados podem estar incompletos.",
        ["warn.porkbunNotConfigured"] = "Verificações de disponibilidade indisponíveis (API Porkbun não configurada no servidor).",
        ["warn.rateLimitRetry"] = "Muitas verificações atingiram o limite do Porkbun. Tente novamente em um minuto.",
        ["warn.hintUseLlm"] = "Tente mais nomes de marca inventados, adicione TLDs como .app ou .dev, ou aumente o limite de preço.",
        ["warn.hintNoLlm"] = "Tente nomes mais curtos, adicione um TLD de país (ex. .br), aumente o limite de preço ou ative a IA.",
        ["warn.noAvailable"] = "Verificados {0} domínios; nenhum disponível abaixo de ${1:F0}. {2}",
        ["warn.aiBriefFailed"] = "Brief de IA falhou, usando alternativa: {0}",
        ["warn.aiAdviceFailed"] = "Análise de IA falhou: {0}",
        ["warn.aiPlannerFailed"] = "Planejador de IA falhou: {0}",
        ["warn.aiPlannerNoValid"] = "O planejador de IA não retornou domínios válidos; verificando nomes heurísticos.",
        ["warn.aiPlannerNoValidQueue"] = "O planejador de IA não retornou domínios válidos; usando fila heurística.",
        ["warn.aiPlannerFailedHeuristic"] = "Planejador de IA falhou: {0}; verificando nomes heurísticos.",
        ["warn.aiPlannerFailedQueue"] = "Planejador de IA falhou, usando fila heurística: {0}",
        ["warn.llmNameGenFailed"] = "Geração de nomes com IA falhou: {0}",
        ["warn.aiRefillFailed"] = "Reabastecimento de IA falhou: {0}",
        ["brief.audience"] = "clientes-alvo deste negócio",
        ["brief.productSummaryEmpty"] = "Um novo negócio em busca de um nome de domínio memorável.",
        ["brief.productSummaryPrefix"] = "Um conceito de negócio descrito como: {0}",
        ["brief.namingStyle1"] = "portmanteaus metafóricos suaves",
        ["brief.namingStyle2"] = "misturas opacas de 8-11 caracteres",
        ["brief.namingStyle3"] = "marcas abstratas inventadas",
        ["brief.vibeMemorable"] = "memorável",
        ["brief.vibeDistinctive"] = "distintivo",
        ["brief.tldStrategy"] = "nomes .com curtos e pronunciáveis costumam estar ocupados; prefira misturas opacas de 8-10 caracteres em .com",
        ["brief.defaultConceptVenture"] = "empresa",
        ["brief.defaultConceptBrand"] = "marca"
    };

    private static readonly Dictionary<string, string> Fr = new()
    {
        ["seo.brandScoring"] = "score de marque",
        ["seo.idealBrandLength"] = "longueur idéale (8-11)",
        ["seo.acceptableCoinedLength"] = "longueur inventée acceptable",
        ["seo.lengthPenalty"] = "pénalité de longueur",
        ["seo.softMetaphorPortmanteau"] = "portemanteau métaphorique doux",
        ["seo.literalPenalty"] = "pénalité littérale '{0}'",
        ["seo.singleConceptEvoked"] = "évoque un seul concept",
        ["seo.keywordMashupPenalty"] = "pénalité mélange de mots-clés",
        ["seo.genericSuffixPenalty"] = "pénalité suffixe générique",
        ["seo.evokes"] = "évoque '{0}'",
        ["seo.matches"] = "correspond à '{0}'",
        ["seo.goodLength"] = "bonne longueur (8-18)",
        ["seo.acceptableLength"] = "longueur acceptable",
        ["seo.longDomain"] = "domaine long",
        ["seo.multiKeywordMatch"] = "correspondance multi-mots-clés",
        ["seo.modifierKeyword"] = "mot modificateur",
        ["seo.genericName"] = "nom générique",
        ["advice.noneFound"] = "Aucun domaine disponible après {0} sur {1} vérifications ({2} pris ou hors budget). Essayez plus de TLD ou relancez une recherche.",
        ["advice.oneFound"] = "Une seule option trouvée : {0}{1}. {2}/{3} noms vérifiés. La plupart étaient pris. Essayez plus de TLD ou relancez la recherche.",
        ["advice.multipleFound"] = "{0} options trouvées après {1}/{2} vérifications ({3} pris ou hors budget). Ajoutez des TLD pour plus de choix.",
        ["warn.rateLimitIncomplete"] = "De nombreuses vérifications ont atteint la limite Porkbun. Les résultats peuvent être incomplets.",
        ["warn.porkbunNotConfigured"] = "Les vérifications de disponibilité sont indisponibles (API Porkbun non configurée sur le serveur).",
        ["warn.rateLimitRetry"] = "De nombreuses vérifications ont atteint la limite Porkbun. Réessayez dans une minute.",
        ["warn.hintUseLlm"] = "Essayez plus de noms de marque inventés, ajoutez des TLD comme .app ou .dev, ou augmentez le plafond de prix.",
        ["warn.hintNoLlm"] = "Essayez des noms plus courts, ajoutez un TLD pays (ex. .fr), augmentez le plafond ou activez l'IA.",
        ["warn.noAvailable"] = "{0} domaines vérifiés ; aucun disponible sous ${1:F0}. {2}",
        ["warn.aiBriefFailed"] = "Échec du brief IA, repli utilisé : {0}",
        ["warn.aiAdviceFailed"] = "Échec de l'analyse IA : {0}",
        ["warn.aiPlannerFailed"] = "Échec du planificateur IA : {0}",
        ["warn.aiPlannerNoValid"] = "Le planificateur IA n'a renvoyé aucun domaine valide ; vérification heuristique.",
        ["warn.aiPlannerNoValidQueue"] = "Le planificateur IA n'a renvoyé aucun domaine valide ; file heuristique utilisée.",
        ["warn.aiPlannerFailedHeuristic"] = "Échec du planificateur IA : {0} ; vérification heuristique.",
        ["warn.aiPlannerFailedQueue"] = "Échec du planificateur IA, file heuristique utilisée : {0}",
        ["warn.llmNameGenFailed"] = "Échec de la génération de noms IA : {0}",
        ["warn.aiRefillFailed"] = "Échec du réapprovisionnement IA : {0}",
        ["brief.audience"] = "clients cibles de cette entreprise",
        ["brief.productSummaryEmpty"] = "Une nouvelle entreprise cherchant un nom de domaine mémorable.",
        ["brief.productSummaryPrefix"] = "Un concept d'entreprise décrit comme : {0}",
        ["brief.namingStyle1"] = "portemanteaux métaphoriques doux",
        ["brief.namingStyle2"] = "mélanges opaques de 8-11 caractères",
        ["brief.namingStyle3"] = "marques abstraites inventées",
        ["brief.vibeMemorable"] = "mémorable",
        ["brief.vibeDistinctive"] = "distinctif",
        ["brief.tldStrategy"] = "les noms .com courts et prononçables sont souvent pris ; préférer des mélanges opaques de 8-10 caractères en .com",
        ["brief.defaultConceptVenture"] = "entreprise",
        ["brief.defaultConceptBrand"] = "marque"
    };

    private static readonly Dictionary<string, string> De = new()
    {
        ["seo.brandScoring"] = "Markenbewertung",
        ["seo.idealBrandLength"] = "ideale Länge (8-11)",
        ["seo.acceptableCoinedLength"] = "akzeptable erfundene Länge",
        ["seo.lengthPenalty"] = "Längenabzug",
        ["seo.softMetaphorPortmanteau"] = "weiches Metapher-Portmanteau",
        ["seo.literalPenalty"] = "wörtliche '{0}'-Strafe",
        ["seo.singleConceptEvoked"] = "ein Konzept angedeutet",
        ["seo.keywordMashupPenalty"] = "Keyword-Mix-Strafe",
        ["seo.genericSuffixPenalty"] = "generisches Suffix-Abzug",
        ["seo.evokes"] = "erinnert an '{0}'",
        ["seo.matches"] = "passt zu '{0}'",
        ["seo.goodLength"] = "gute Länge (8-18)",
        ["seo.acceptableLength"] = "akzeptable Länge",
        ["seo.longDomain"] = "lange Domain",
        ["seo.multiKeywordMatch"] = "Mehrfach-Keyword-Treffer",
        ["seo.modifierKeyword"] = "Modifikator-Keyword",
        ["seo.genericName"] = "generischer Name",
        ["advice.noneFound"] = "Keine verfügbaren Domains nach {0} von {1} Prüfungen ({2} belegt oder über Budget). Mehr TLDs oder neue Suche versuchen.",
        ["advice.oneFound"] = "Nur eine Option gefunden: {0}{1}. {2}/{3} Namen geprüft. Die meisten waren belegt. Mehr TLDs oder erneut suchen.",
        ["advice.multipleFound"] = "{0} Optionen nach {1}/{2} Prüfungen ({3} belegt oder über Budget). Mehr TLDs für weitere Auswahl.",
        ["warn.rateLimitIncomplete"] = "Viele Prüfungen trafen das Porkbun-Limit. Ergebnisse können unvollständig sein.",
        ["warn.porkbunNotConfigured"] = "Verfügbarkeitsprüfungen nicht verfügbar (Porkbun-API auf dem Server nicht konfiguriert).",
        ["warn.rateLimitRetry"] = "Viele Prüfungen trafen das Porkbun-Limit. Bitte in einer Minute erneut versuchen.",
        ["warn.hintUseLlm"] = "Mehr erfundene Markennamen, TLDs wie .app oder .dev, oder höheres Preislimit versuchen.",
        ["warn.hintNoLlm"] = "Kürzere Namen, Landes-TLD (z. B. .de), höheres Preislimit oder KI aktivieren.",
        ["warn.noAvailable"] = "{0} Domains geprüft; keine unter ${1:F0} verfügbar. {2}",
        ["warn.aiBriefFailed"] = "KI-Brief fehlgeschlagen, Fallback: {0}",
        ["warn.aiAdviceFailed"] = "KI-Analyse fehlgeschlagen: {0}",
        ["warn.aiPlannerFailed"] = "KI-Planer fehlgeschlagen: {0}",
        ["warn.aiPlannerNoValid"] = "KI-Planer lieferte keine gültigen Domains; heuristische Namen werden geprüft.",
        ["warn.aiPlannerNoValidQueue"] = "KI-Planer lieferte keine gültigen Domains; heuristische Warteschlange wird verwendet.",
        ["warn.aiPlannerFailedHeuristic"] = "KI-Planer fehlgeschlagen: {0}; heuristische Namen werden geprüft.",
        ["warn.aiPlannerFailedQueue"] = "KI-Planer fehlgeschlagen, heuristische Warteschlange: {0}",
        ["warn.llmNameGenFailed"] = "KI-Namensgenerierung fehlgeschlagen: {0}",
        ["warn.aiRefillFailed"] = "KI-Nachfüllen fehlgeschlagen: {0}",
        ["brief.audience"] = "Zielkunden für dieses Geschäft",
        ["brief.productSummaryEmpty"] = "Ein neues Unternehmen auf der Suche nach einer einprägsamen Domain.",
        ["brief.productSummaryPrefix"] = "Ein Geschäftskonzept beschrieben als: {0}",
        ["brief.namingStyle1"] = "weiche Metapher-Portmanteaus",
        ["brief.namingStyle2"] = "8-11 Zeichen undurchsichtige Mischungen",
        ["brief.namingStyle3"] = "abstrakte erfundene Marken",
        ["brief.vibeMemorable"] = "einprägsam",
        ["brief.vibeDistinctive"] = "unverwechselbar",
        ["brief.tldStrategy"] = "kurze aussprechbare .com-Namen sind meist belegt; 8-10 Zeichen undurchsichtige Mischungen auf .com bevorzugen",
        ["brief.defaultConceptVenture"] = "unternehmen",
        ["brief.defaultConceptBrand"] = "marke"
    };

    private static readonly Dictionary<string, Dictionary<string, string>> Strings = new(StringComparer.Ordinal)
    {
        ["en"] = En,
        ["es"] = Es,
        ["pt"] = Pt,
        ["fr"] = Fr,
        ["de"] = De
    };
}
